### ISSUE TITLE
toClick() method seems not to work in cucumber tests

### ISSUE THREAD

**Issue by Raulpemol** [Arquisoft/viade_en2a#184]
When coding acceptance tests with cucumber and trying to test the log in functionallity, clicking on the Login button does not either load the next view nor it shows an error.

To see the code regarding this test follow this steps:
1. Go to "ListFriendRoutes" branch.
2. In the folder "e2e/step_definitions" open the file viewFriendRoutes.steps.js.
3. The statement is the one which clicks a button in the first test function.

**Comment by pglez82** [comment]
I am not able to find any branch with the name ListFriendRoutes.

**Comment by Raulpemol** [comment]
ListFriendsView, my mistake.

**Comment by pglez82** [comment]
Ok. After some investigation I found a few problems with your tests:

1. First thing, I think there is a misunderstanding here. Jest puppeter doesn't run the tests in the browser that you see launching when you run `npm run test:e2e` (that one is launched by npm start). It uses chromium. The thing is that this chromium by default is headless (so it runs well in travis). For debugging is quite useful to see what your tests are doing so you can configure chromium in no headless mode. You need to add this at the end of file `jest-puppeteer.config.js`:
```
launch: {
        headless: false,
        devtools: true
      }
```


2. In your tests, the cucumber descriptions are not matching the descriptions that you write in the steps. You need to remove the quotes and make this texts match (for instance I click the "Back" button does not match with I click the 'Back' button). 

3. Your button select is far too complicated. I have tried with `await expect(page).toClick('button[type=submit]')` and it works.

4. If you need to stop the tests in order to see what is happening in chromium is useful to use the instruction `await jestPuppeteer.debug()`. That will help you see what is happening with the tests.

With this changes I was able to fill the input text with alice webid and click the login button (and see this actions in chromium). 

Try it and let me know if it helps.

**Comment by Raulpemol** [comment]
The problem with the quotes was already fixed in the local branch, so we will try with the selector you are proposing. Thanks in advance.

**Comment by pglez82** [comment]
Ok. For the next time, make sure that I have access to the last version of the code so I am not looking over already fixed errors. And also, it is important that you change the configuration to see chromium. It will help you a low debugging the tests.

**Comment by sarav22** [comment]
I tried these changes in the branch "cucumber-fix" and now I have other mistakes that did not appear before. I get "Execution context was destroyed, most likely because of a navigation.".
Sometimes I also get "ERROR: el proceso con PID 12632 (proceso secundario de PID 14132)
no se pudo terminar.
Motivo: No hay ninguna instancia activa de la tarea." in the console.

**Comment by pglez82** [comment]
Did you make it work?

**Comment by sarav22** [comment]
Well, it works if you restart the computer. I don't know if it's something wrong with my console or computer, but once I restart it, the first time everything works. The next times I run the tests, the errors I mentioned before start appearing.
